M48
; DRILL file {KiCad 9.0.7-9.0.7~ubuntu22.04.1} date 2026-04-30T10:19:36-0500
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-04-30T10:19:36-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7-9.0.7~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.000
%
G90
G05
T1
X55.0Y-55.0
X55.0Y-120.0
X115.0Y-55.0
X115.0Y-120.0
M30
